### ISSUE TITLE
History/About: Array of Albums shown on cards 

### ISSUE THREAD

**Issue by sarahholder** [nss-evening-cohort-11/bands-scuurvy#11]
##User Story
As a user, at the bottom of the page I will see 3 cards in a row that includes an image of the album cover, an album title above the image.

##AC
WHEN the page loads 
THEN I should be able to scroll to the bottom of the page and 2 bootstrap cards containing square images of the 3 past albums will display in a row on separate cards with h2 tag containing title above image.
 

## Dev Notes
In the index add a div with an id= `album-list`. class `d-flex flex-wrap`
Create an array called `albumsArr` that includes the last 3 albums, the title and a track list. 
Use bootstrap cards, card decks:
`https://getbootstrap.com/docs/4.0/components/card/#card-decks`
Create a `printToDom` function - that takes in an `divId` and `textToPrint`
create a `albumBuilder` function - that takes in a array `builderArr` loops over the array and builds a `domString` containing a `div` card container with a class of `album-card col-3`. Then lists an h2 tag for album-title, image below album-title.

**Comment by sarahholder** [comment]
![album titles](https://user-images.githubusercontent.com/59459651/73900154-770cc600-4854-11ea-81e4-1926eba5a1ee.PNG)

**Comment by sarahholder** [comment]
![Album](https://user-images.githubusercontent.com/59459651/73900261-ceab3180-4854-11ea-9bff-2a7b7b5325a3.PNG)

**Comment by sarahholder** [comment]
group decided on dark charcoal background with gray outline.

**Comment by zoeames** [comment]
tell me more about this:  "and below that will be a button to drop down track list and when pushed again will hide track list."
