### ISSUE TITLE
printToDom function for JS page

### ISSUE THREAD

**Issue by lstar18** [nss-evening-cohort-11/bands-scuurvy#15]
## User Story
As a user, the content of the page should load when I open the page
## AC
WHEN the printToDom function is called
THEN the content that needs to show on the page appears
AND all items in domString are printed
## Dev Notes
create `const printToDom` function with (divId,textToPrint)

**Comment by zoeames** [comment]
this should not be its own ticket - it doesn't deliver any functionality
