### ISSUE TITLE
History/About: button to show list of track titles on album card

### ISSUE THREAD

**Issue by sarahholder** [nss-evening-cohort-11/bands-scuurvy#19]
## User Story
As a user, when I scroll to the bottom of the page I should see buttons listed under each album featured on page. That button when clicked will drop down a list of tracks included on the pictured album.

## AC
WHEN I am on the about page and scroll to bottom 
THEN I should see images of 3 previous albums with album-title above the image and a button labeled 'ALBUM TRACKS' below the image of album.
AND when button is the album card reprints including the track list. 
## DEV Notes
* Add a button to the domString for each album card. 
* The buttons should have this bootstrap styling <button type="button" class="btn btn-outline-danger">Danger</button>
* each button will have a unique id=(insert album title).
* An eventlistener `click` should be added to each of these buttons using `document.getElementById`
* The eventlistener should activate a function called `tracklistBuilder` that loops over the `builderArr` for the selected album and add the tracklist to the each album card as it is reprinted based on the eventlistener `click`.

**Comment by sarahholder** [comment]
![Capture](https://user-images.githubusercontent.com/59459651/74183230-2c030200-4c0a-11ea-8e6d-ca1d681f11af.PNG)

**Comment by zoeames** [comment]
this ticket needs more dev details.  probably something about an event listener?

**Comment by lstar18** [comment]
class="btn btn-danger"
